//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class AliciLog
    {
        public int İslemId { get; set; }
        public int KullaniciId { get; set; }
        public string AlınanUrun { get; set; }
        public decimal AlisMiktari { get; set; }
        public decimal AlisFiyati { get; set; }
        public System.DateTime AlisTarihi { get; set; }
        public decimal AlistakiVergi { get; set; }
        public decimal ToplamHarcama { get; set; }
    }
}
