//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borsa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeriTabaniEntities : DbContext
    {
        public VeriTabaniEntities()
            : base("name=VeriTabaniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTbl> AdminTbl { get; set; }
        public virtual DbSet<AliciIstekTbl> AliciIstekTbl { get; set; }
        public virtual DbSet<KullaniciTbl> KullaniciTbl { get; set; }
        public virtual DbSet<OnayTbl> OnayTbl { get; set; }
        public virtual DbSet<SatistakiUrunTbl> SatistakiUrunTbl { get; set; }
    }
}
